<a href="https://colab.research.google.com/github/Plucinski/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print('hello colab')

hello colab


In [4]:
print('hello world')

hello world


teraz sekcja nr 3

In [6]:
import numpy as np

In [14]:
A = np.array([[3,1],[2,1]])
B = np.array([[1,1],[1,1]])
print (A+B)

[[4 2]
 [3 2]]


teraz sekcja nr 3

In [15]:
np.random.seed(0)

In [27]:
np.random.randn()

1.454273506962975

In [34]:
np.random.rand()

0.7781567509498505

In [37]:
np.random.randint(low=1, high=6, size = 10)

array([1, 1, 5, 1, 5, 2, 5, 2, 3, 3])

In [53]:
A = np.arange(start=1, stop=21)

In [54]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
A[2]

np.int64(3)